image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - "editorconfig.editorconfig"
    - "ms-vscode.sublime-keybindings"
    - "dracula-theme.theme-dracula"
    - "ms-python.python"
tasks:
- init: |
    source "$HOME"/.poetry/env \
    && ${HOME}/.poetry/bin/poetry config virtualenvs.create "true" \
    && ${HOME}/.poetry/bin/poetry config virtualenvs.in-project "true" \
    && poetry install
- name: VirutalEnv
  init: source ${HOME}/.venv/bin/activate
