image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - "editorconfig.editorconfig"
    - "ms-vscode.sublime-keybindings"
    - "dracula-theme.theme-dracula"
    - "ms-python.python"
tasks:
- init: |
    poetry env use python && poetry install
