image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - "editorconfig.editorconfig"
    - "ms-vscode.sublime-keybindings"
    - "dracula-theme.theme-dracula"
    - "ms-python.python"
tasks:
- init: poetry install
- name: VirutalEnv
  init: source .venv/bin/activate
