image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - "editorconfig.editorconfig"
    - "ms-vscode.sublime-keybindings"
    - "dracula-theme.theme-dracula"
    - "ms-python.python"
tasks:
- init: |
    source "$HOME"/.poetry/env \
    && poetry config virtualenvs.create "true" \
    && poetry config virtualenvs.in-project "true" \
    && poetry install
