image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - "editorconfig.editorconfig"
    - "ms-vscode.sublime-keybindings"
    - "dracula-theme.theme-dracula"
    - "ms-python.python"
tasks:
- init: |
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - \
    && "export PATH=\"\${HOME}/.poetry/bin\":\$PATH" >> /home/gitpod/.bashrc \
    && source "$HOME"/.poetry/env \
    && ${HOME}/.poetry/bin/poetry config virtualenvs.create "true" \
    && ${HOME}/.poetry/bin/poetry config virtualenvs.in-project "true" \
    && poetry install
