- name: Setup AWS with OpenID Connect Provider, DynamoDB and RDS PostgreSQL with VPC Peering
  hosts: localhost
  connection: local

  collections:
    - kameshsampath.demos
    -
  vars:
    oidc_bucket_name: rosa-demos-oidc
    rollback: false
    aws_region: us-west-2
    iam: true
    rds: true
    dynamodb: true
    rosa_cluster_name: my-rosa-cluster

  roles:
    - kameshsampath.demos.rosa_demos
