name: Release Artifacts

on:
  release:
    types:
      - released

jobs:
  ansible-builder-ee:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: openshift-demos-ansible-ee
      IMAGE_TAGS: latest
    strategy:
      matrix:
        python-version:
          - 3.8
    steps:

#      - name: "Dump GitHub Context"
#        env:
#          GITHUB_CONTEXT: "${{ toJson(github) }}"
#        run: |
#          echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2
        with:
          ref: "${{ github.event.ref }}"

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        run: |
          pip install poetry && poetry install

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
          logout: true

      - name: Build the Ansible EE Image
        id: build-image
        run: |
          poetry env use python
          poetry ansible-builder build --tag $IMAGE_TAG
          podman push $IMAGE_TAG
          podman tag $IMAGE_TAG $IMAGE_LATEST
          podman push $IMAGE_LATEST
        env:
          IMAGE_TAG: "${{ secrets.QUAYIO_REPO }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}"
          IMAGE_LATEST: "${{ secrets.QUAYIO_REPO }}/${{ env.IMAGE_NAME }}:latest"
        working-directory: ${{ github.workspace }}/builder-ee
  site:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ github.event.ref }}"

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        run: |
          pip install poetry && poetry install

      - name: Generate Docs
        run: |
          make all
        working-directory: "${{ github.workspace }}/documentation"

      - name: Deploy Site
        id: deploy_site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ github.workspace }}/documentation/build/html"
          publish_branch: "gh-pages"
          full_commit_message: "[Release]${{ github.event.head_commit.message }}"
